---
title: "Deep Learning with R - Chapter 2"
subtitle: "Francois Chollet and J.J. Allaire"
author: "You Zhou (email) and Federico Marini (marinif@uni-mainz.de)</br>"
date: "2020/11/23</br>
  IMBEI - University Medical Center Mainz"
output:
  xaringan::moon_reader:
    css: ["default", "default-fonts","css/FMstyles.css","css/animate.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      # ratio: "16:9"
      titleSlideClass: [center, middle]
---

layout: true

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  eval = TRUE,
  message = FALSE,
  echo = TRUE,
  warnings = FALSE,
  fig.align = "center"
)
```


---

[from here: YOU]

# Chapter 2 Agenda

**Before we begin: the mathematical building blocks of neural networks**

- content1
- content2
- content3

A first example of a neural network

Tensors and tensor operations

How neural networks learn via backpropagation and gradient descent

---


# A first look at a neural network


---


# Data representations for neural networks


---

# The gears of neural networks: tensor operations





---

[from here: FEDE]

# Tensor operations: tensor dot

# Tensor operations: tensor reshaping

# Tensor operations: A geometric interpretation 

---

# The engine of neural networks: gradient-based optimization

What’s a derivative?

Derivative of a tensor operation

SGD

Chaining derivatives


---

# Looking back at 1st example


---

# Summary




---

# Useful links

https://github.com/jjallaire/deep-learning-with-r-notebooks

https://www.manning.com/books/deep-learning-with-r -> Source code

(Git version recommended!)

---

class: middle, center

# Thank you all for your attention!

Next meeting: 



