# Chapter 3 Lab: Linear Regression

```{r}
library("MASS")
library("ISLR")
```

# Simple Linear Regression

```{r error=TRUE}
head(Boston)
names(Boston)
?Boston
summary(Boston)

plot(Boston$lstat, Boston$medv)

lm.fit <- lm(medv~lstat)
lm.fit <- lm(medv~lstat, data = Boston)
lm.fit
summary(lm.fit)
names(lm.fit)
coef(lm.fit)
confint(lm.fit)

predict(lm.fit, data.frame(lstat = (c(5, 10, 15))), interval = "confidence")
predict(lm.fit, data.frame(lstat = (c(5, 10, 15))), interval = "prediction")
plot(Boston$lstat, Boston$medv)

# Check the fit
abline(lm.fit)
abline(lm.fit, lwd = 3)
abline(lm.fit, lwd = 3, col = "red")
plot(Boston$lstat, Boston$medv, col = "red")
plot(Boston$lstat, Boston$medv, pch = 20)
plot(Boston$lstat, Boston$medv, pch = "+")
plot(1:20, 1:20, pch = 1:20)
par(mfrow = c(2,2))
plot(lm.fit)
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))
```

# Multiple Linear Regression

```{r}
lm.fit <- lm(medv~lstat + age, data = Boston)
lm.fit
summary(lm.fit)
lm.fit <- lm(medv~., data = Boston)
summary(lm.fit)

library("car")
vif(lm.fit)
lm.fit1 <- lm(medv~.-age, data = Boston)
summary(lm.fit1)
lm.fit1 <- update(lm.fit, ~.-age)
```

# Interaction Terms

```{r}
summary(lm(medv~lstat*age, data = Boston))
```

# Non-linear Transformations of the Predictors

```{r}
lm.fit2 <- lm(medv~lstat + I(lstat^2), data = Boston)
summary(lm.fit2)

lm.fit <- lm(medv~lstat, data = Boston)
summary(lm.fit)

anova(lm.fit, lm.fit2)

par(mfrow = c(2,2))
plot(lm.fit2)

lm.fit5 <- lm(medv~poly(lstat, 5), data = Boston)
summary(lm.fit5)

# logging one of the predictors
summary(lm(medv~log(rm), data = Boston))
```

# Qualitative Predictors

```{r}
head(Carseats)
dim(Carseats)
names(Carseats)
lm.fit <- lm(Sales~. + Income:Advertising + Price:Age, data = Carseats)
summary(lm.fit)
# attach(Carseats)
contrasts(Carseats$ShelveLoc)
```

# Writing Functions

```{r}
LoadLibraries <- function() {
 library("ISLR")
 library("MASS")
 print("The libraries have been loaded.")
}
LoadLibraries()
```


```{r}
sessionInfo()
```

